### ISSUE TITLE
Swift 4.2 support

### ISSUE THREAD

**Issue by artemnovichkov** [kitefaster/kitemetrics_iOS#5]
Are you going to add Swift 4.2 compatibility?

**Comment by kitefaster** [comment]
Yes.  Soon.  Thanks for your pull request.

In the mean time you can still use Kitemetrics with your Swift 4.2 project by changing the Kitemetrics Target language to Swift 4.0.

From the project navigator select the "Pods" project. Select the Kitemetrics Target. Go the the "Build Settings" tab. Search for Swift Language Version. Change the language from "Swift 4.0" to "Swift 3.2".

**Comment by kitefaster** [comment]
Kitemetrics version 1.1.10 is now available in Swift 4.2

**Comment by artemnovichkov** [comment]
Sorry, but I can't install 1.1.10 version via Cocoapods

**Comment by kitefaster** [comment]
Please run `pod update Kitemetrics`
