### ISSUE TITLE
A number of Warnings are appearing in Xcode 11

### ISSUE THREAD

**Issue by ethanwa** [kitefaster/kitemetrics_iOS#9]
<img width="428" alt="Screen Shot 2019-09-13 at 10 39 49 PM" src="https://user-images.githubusercontent.com/1653780/64902614-80fd1500-d678-11e9-8bf6-361c21c74d82.png">

**Comment by kitefaster** [comment]
Warnings resolved in Kitemetrics version 1.1.11.  Run "pod update".
